include:
  # Base Services
  # - ./nginx-proxy-manager/docker-compose.yml
  - ./cloudflared/docker-compose.yml
  - ./watchtower/docker-compose.yml

  # Applications
  # - ./flowise/docker-compose.yml
  # - ./homarr/docker-compose.yml
  # - ./mongo/docker-compose.yml
  - ./n8n/docker-compose.yml
  # - ./open-webui/docker-compose.yml
  # - ./portainer/docker-compose.yml
  # - ./searxng/docker-compose.yml
  # - ./stremio/docker-compose.yml
  - ./wg-easy/docker-compose.yml

networks:
  public:
    name: public
    driver: bridge
