services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true # Clean up old images after update
      - WATCHTOWER_POLL_INTERVAL=86400 # Check for updates once a day (in seconds)
    networks:
      - public
# networks:
#   public:
#     external: true
